services:
  app:
    build:
      context: .
    ports:
      - 8082:8080
    depends_on:
      - mongo
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri":"mongodb://mongo:27017/parquimetro"
        }'
    networks:
      - app-network
    deploy:
      replicas: 3

  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27017:27017
    volumes:
      - my-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: 'mongo-express:1.0.2'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: grupo5
      ME_CONFIG_BASICAUTH_PASSWORD: abc12345
    networks:
      - app-network

volumes:
  my-data:

networks:
  app-network:
    driver: bridge
